### ISSUE TITLE
Error when loading cl-neo4j

### ISSUE THREAD

**Issue by dcguim** [kraison/cl-neo4j#4]
If I call slime (using SBCL and Emacs) and a simple quicklisp`s load command reports an error:
> M-x slime
```lisp
(ql:quickload :cl-neo4j)
```
There is no class named CL-NEO4J::CYPHER-QUERY.
   [Condition of type SIMPLE-ERROR]

Backtrace:
  0: (SB-PCL::FIND-CLASS-FROM-CELL CL-NEO4J::CYPHER-QUERY #<SB-KERNEL::CLASSOID-CELL CL-NEO4J::CYPHER-QUERY> T)
  1: ((SB-C::TOP-LEVEL-FORM (SB-PCL::LOAD-DEFMETHOD (QUOTE STANDARD-METHOD) (QUOTE CL-NEO4J::ENCODE-NEO4J-JSON-PAYLOAD) (QUOTE NIL) (LIST (FIND-CLASS (QUOTE CL-NEO4J::CYPHER-QUERY)) (SB-MOP:INTERN-EQL-SPEC..
  2: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /Users/dcguim/.cache/common-lisp/sbcl-1.2.11-macosx-x64/Users/dcguim/common-lisp/cl-neo4j/src/utilities..
  3: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /Users/dcguim/.cache/common-lisp/sbcl-1.2.11-macosx-x64/Users/dcguim/common-lisp/cl-neo4j/src/utilities.fasl" {1006950C93}> NIL NIL) 
...

I believe this will be reproducible by just trying to load cl-neo4j with quicklisp

**Comment by kraison** [comment]
Hmm, I can't reproduce this from the master branch nor loading fresh from Quicklisp.  Can you share some more detail about your environment?  Which version of Quicklisp are you using and which version of cl-neo4j is it providing?  When I load via Quicklisp, I get cl-neo4j-release-b8ad637a-git, which works for me.

**Comment by kraison** [comment]
I wonder if you aren't getting an older version of cl-neo4j.  Take a look at commit https://github.com/kraison/cl-neo4j/commit/969efe1180c4f5d4bec77338114ef925a4a4b60d;  I believe that commit fixed the problem that you are having.

**Comment by dcguim** [comment]
My quicklisp version is: 2015-06-16

```lisp
(ql:system-apropos "cl-neo4j")
#<SYSTEM cl-neo4j / cl-neo4j-release-b8ad637a-git / quicklisp 2015-06-08>
#<SYSTEM cl-neo4j.tests / cl-neo4j-release-b8ad637a-git / quicklisp 2015-06-08>
; No value
```
Thanks, I`ll check the commit 969efe1.
You are right my local repo was 2 commits behind bcaa7d147d5d703ea298298d767c31fe5c2ff6bb.
